dependencies:
    module:
      - basic_auth
      - node
      - serialization
      - user
id: entity.node
plugin_id: 'entity:node'
granularity: resource
configuration:
  methods:
    - GET
    - POST
    - DELETE
    - PATCH
  formats:
    - json
  authentication:
    - basic_auth
