dependencies:
    module:
      - basic_auth
      - developer_app
      - serialization
      - user
id: entity.developer_app
plugin_id: 'entity:developer_app'
granularity: resource
configuration:
  methods:
    - GET
    - POST
    - DELETE
    - PATCH
  formats:
    - json
  authentication:
    - basic_auth
