dependencies:
    module:
      - basic_auth
      - apidoc
      - serialization
      - user
id: entity.apidoc
plugin_id: 'entity:apidoc'
granularity: resource
configuration:
  methods:
    - GET
    - POST
    - DELETE
    - PATCH
  formats:
    - json
  authentication:
    - basic_auth
