dependencies:
    module:
      - basic_auth
      - api_product
      - serialization
      - user
id: entity.api_product
plugin_id: 'entity:api_product'
granularity: resource
configuration:
  methods:
    - GET
    - POST
    - DELETE
    - PATCH
  formats:
    - json
  authentication:
    - basic_auth
